#!/bin/bash

SOURCE=`readlink -n "$BASH_SOURCE" || echo $BASH_SOURCE`	# allow finding enclosing directory even if through a symlink
BASEDIR="$(cd `dirname "$SOURCE"`/..; pwd)"

for f in $(ls -1 "$BASEDIR/source/")
do source "$BASEDIR/source/$f"
done

for f in $(ls -1 "$BASEDIR/functions")
do source "$BASEDIR/functions/$f"
done

export EDITOR='/Applications/Sublime Text.app/Contents/MacOS/sublime_text'

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Init rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Prevent commands beginning with a space to be added to the history
# Credit: http://stackoverflow.com/questions/640403
HISTCONTROL='ignoredups:ignorespace'

echo "								Woudzigouga Bougou D'Négué !"
